/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ahmadgilang.apps;

import com.ahmadgilang.apps.entity.Customer;
import com.ahmadgilang.apps.entity.Employee;
import com.ahmadgilang.apps.entity.Order;
import com.ahmadgilang.apps.entity.OrderDetail;
import com.ahmadgilang.apps.entity.ShippingMethod;
import com.ahmadgilang.apps.repository.CustomerRepository;
import com.ahmadgilang.apps.repository.EmployeeRepository;
import com.ahmadgilang.apps.repository.OrderRepository;
import com.ahmadgilang.apps.repository.ShippingMethodRepository;
import com.ahmadgilang.apps.utils.EngineUtils;
import com.ahmadgilang.apps.utils.RightRendering;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author asus
 */
public class MonitoringOrder extends javax.swing.JFrame {
    public TableCellRenderer right = new RightRendering();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private int globalIndex = 0;
    
    public List<Customer> listCustomer;
    public List<Employee> listEmployee;
    public List<ShippingMethod> listShippingMethod;
    public List<Order> listOrder;
    public List<OrderDetail> listOrderDetail;
    
    /**
     * Creates new form MonitoringOrder
     */
    public MonitoringOrder() {
        initComponents();
        composeCustomer();
        composeEmployee();
        composeShippingMethod();
        composeData();
        getSpesificRow(listOrder, "first");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbEmployee = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbShippingMethod = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPoNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtShipDate = new javax.swing.JTextField();
        txtOrderSubtotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTaxes = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtShippingAndHandling = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtOrderTotal = new javax.swing.JTextField();
        btnFirstRow = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLastRow = new javax.swing.JButton();
        txtOrderId = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Order Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Orders");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Customer : ");

        cmbCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomerActionPerformed(evt);
            }
        });

        cmbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee : ");

        jLabel4.setText("Shipping Method : ");

        cmbShippingMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShippingMethodActionPerformed(evt);
            }
        });

        jLabel5.setText("Order ID : ");

        jLabel6.setText("Order Date : ");

        txtOrderDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderDateActionPerformed(evt);
            }
        });

        jLabel7.setText("PO Number :");

        txtPoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoNumberActionPerformed(evt);
            }
        });

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        jLabel8.setText("Comment :");

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableProduct);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Ship Date :");

        txtShipDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShipDateActionPerformed(evt);
            }
        });

        txtOrderSubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOrderSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderSubtotalActionPerformed(evt);
            }
        });

        jLabel10.setText("Order Subtotal :");

        jLabel11.setText("Taxes :");

        txtTaxes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTaxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaxesActionPerformed(evt);
            }
        });

        jLabel12.setText("Shipping and Handling :");

        txtShippingAndHandling.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtShippingAndHandling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShippingAndHandlingActionPerformed(evt);
            }
        });

        jLabel13.setText("Order Total");

        txtOrderTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOrderTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtShipDate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(txtShippingAndHandling, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtOrderSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtShipDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtOrderSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtShippingAndHandling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFirstRow.setText("<<");
        btnFirstRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstRowActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLastRow.setText(">>");
        btnLastRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastRowActionPerformed(evt);
            }
        });

        txtOrderId.setEnabled(false);
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbShippingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOrderDate)
                            .addComponent(txtPoNumber)
                            .addComponent(txtOrderId)))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFirstRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLastRow)
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbShippingMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPoNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirstRow)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnLastRow))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void composeCustomer(){
        listCustomer = new ArrayList<>();
        
        try{
           listCustomer = CustomerRepository.getAllCustomer();
        }catch(Exception e){
            e.printStackTrace();
        }
        
        cmbCustomer.removeAllItems();
        for (Customer customer : listCustomer) {
             cmbCustomer.addItem(customer.getCompanyName());
        }
    }
    
    public void composeEmployee(){
        listEmployee = new ArrayList<>();
        
        try{
           listEmployee = EmployeeRepository.getAllEmployee();
        }catch(Exception e){
            e.printStackTrace();
        }
        
        cmbEmployee.removeAllItems();
        for (Employee employee : listEmployee) {
             cmbEmployee.addItem(employee.getFirstName() + ", " + employee.getLastName());
        }
    }
    
    public void composeShippingMethod(){
        listShippingMethod = new ArrayList<>();
        
        try{
           listShippingMethod = ShippingMethodRepository.getAllShippingMethod();
        }catch(Exception e){
            e.printStackTrace();
        }
        
        cmbShippingMethod.removeAllItems();
        for (ShippingMethod shippingMethod : listShippingMethod) {
             cmbShippingMethod.addItem(shippingMethod.getShippingMethod());
        }
    }
    
    public void getSpesificRow(List<Order> listOrder,String index){
        Order order = new Order();
        if("first".equals(index)){
            globalIndex = 0;
            order = listOrder.get(0); 
        }else if("last".equals(index)){
            globalIndex = listOrder.size() - 1;
            order = listOrder.get(listOrder.size() - 1);
        }else if("previous".equals(index)){
            globalIndex--;
            if(globalIndex < 0){
               JOptionPane.showMessageDialog(null, "This is the first data");
               globalIndex = 0;
               return;
            }
            
            order = listOrder.get(globalIndex);
        }else if("next".equals(index)){
            globalIndex++;
            if(globalIndex > listOrder.size() - 1){
               JOptionPane.showMessageDialog(null, "This is the last data");
               globalIndex = listOrder.size() - 1;
               return;
            }
            order = listOrder.get(globalIndex);
        }
        setData(order);
    }
    
    public void setData(Order order){
        if(order != null){
            cmbCustomer.setSelectedItem(order.getCustomer().getCompanyName());
            cmbEmployee.setSelectedItem(order.getEmployee().getFirstName()+", "+order.getEmployee().getLastName());
            cmbShippingMethod.setSelectedItem(order.getShippingMethod().getShippingMethod());
            txtOrderId.setText(""+order.get_id());
            if(order.getOrderDate() != null){
                txtOrderDate.setText(EngineUtils.formatDate(order.getOrderDate()));
            }else{
                txtOrderDate.setText("");
            }
            txtPoNumber.setText(order.getPurchaseOrderNumber());
            txtComment.setText(order.getComment());
            if(order.getShipDate() != null){
                txtShipDate.setText(EngineUtils.formatDate(order.getShipDate()));
            }else{
                txtShipDate.setText("");
            }
            txtTaxes.setText(EngineUtils.formatAmount(order.getTaxes()));
            txtShippingAndHandling.setText(EngineUtils.formatAmount(order.getFreightCharge()));
            
            listOrderDetail = new ArrayList<>();
            listOrderDetail = order.getListOrderDetail();
            BigDecimal subTotal = showTableProduct(listOrderDetail);
            txtOrderSubtotal.setText(EngineUtils.formatAmount(subTotal));
            
            BigDecimal orderTotal = subTotal.add(order.getTaxes()).add(order.getFreightCharge());
            txtOrderTotal.setText(EngineUtils.formatAmount(orderTotal));
        }
    }
    
    public void composeData(){
        listOrder = new ArrayList<>();
        
        try{
           listOrder = OrderRepository.getAllOrder();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public BigDecimal showTableProduct(List<OrderDetail> listOrderDetail){
        BigDecimal subTotal = BigDecimal.ZERO;
        
        DefaultTableModel tablebook = new DefaultTableModel();
        tablebook.addColumn("Product");
        tablebook.addColumn("Quantity");
        tablebook.addColumn("Unit Price");
        tablebook.addColumn("Discount");
        tablebook.addColumn("Extended Price");
        try{
            for (int i = 0; i < listOrderDetail.size(); i++) {
                OrderDetail orderDetail = listOrderDetail.get(i);
                
                BigDecimal total = orderDetail.getUnitPrice().multiply(new BigDecimal(orderDetail.getQuantity()));
                BigDecimal discount = (total.multiply(orderDetail.getDiscount())).divide(new BigDecimal("100"));
                BigDecimal extendedPrice = total.subtract(discount);
                subTotal = subTotal.add(extendedPrice);
                
                tablebook.addRow(new Object[]{orderDetail.getProduct().getProductName(), orderDetail.getQuantity(),
                    EngineUtils.formatAmount(orderDetail.getUnitPrice()), orderDetail.getDiscount() +"%", EngineUtils.formatAmount(extendedPrice)});
            }
            tableProduct.setModel(tablebook);
            tableProduct.getColumnModel().getColumn(1).setCellRenderer( right );
            tableProduct.getColumnModel().getColumn(2).setCellRenderer( right );
            tableProduct.getColumnModel().getColumn(3).setCellRenderer( right );
            tableProduct.getColumnModel().getColumn(4).setCellRenderer( right );
        }catch (Exception e){
            e.printStackTrace();
        }
        
        return subTotal;
    }
    
    private void txtOrderDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderDateActionPerformed

    private void txtPoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoNumberActionPerformed

    private void txtShipDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShipDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShipDateActionPerformed

    private void txtOrderSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderSubtotalActionPerformed

    private void txtTaxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaxesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaxesActionPerformed

    private void txtShippingAndHandlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShippingAndHandlingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShippingAndHandlingActionPerformed

    private void txtOrderTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderTotalActionPerformed

    private void cmbCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_cmbCustomerActionPerformed

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void cmbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbEmployeeActionPerformed

    private void cmbShippingMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShippingMethodActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbShippingMethodActionPerformed

    private void btnFirstRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstRowActionPerformed
        // TODO add your handling code here:
        getSpesificRow(listOrder, "first");
    }//GEN-LAST:event_btnFirstRowActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        getSpesificRow(listOrder, "previous");
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        getSpesificRow(listOrder, "next");
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastRowActionPerformed
        // TODO add your handling code here:
        getSpesificRow(listOrder, "last");
    }//GEN-LAST:event_btnLastRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitoringOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitoringOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitoringOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitoringOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitoringOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstRow;
    private javax.swing.JButton btnLastRow;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbEmployee;
    private javax.swing.JComboBox<String> cmbShippingMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtOrderSubtotal;
    private javax.swing.JTextField txtOrderTotal;
    private javax.swing.JTextField txtPoNumber;
    private javax.swing.JTextField txtShipDate;
    private javax.swing.JTextField txtShippingAndHandling;
    private javax.swing.JTextField txtTaxes;
    // End of variables declaration//GEN-END:variables
}
